const DEFAULT_DEVICES=['Tripod','Kamera','TV','Lampu 1','Lampu 2','Laptop','Kebersihan'];
let devices=JSON.parse(localStorage.getItem('wk_devices')||'null')||DEFAULT_DEVICES;
let studios=JSON.parse(localStorage.getItem('wk_studios')||'null')||['Studio 1'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
$('#date').value=new Date().toISOString().slice(0,10);
$('#scriptUrl').value=localStorage.getItem('wk_script_url')||'';
function save(){localStorage.setItem('wk_devices',JSON.stringify(devices));localStorage.setItem('wk_studios',JSON.stringify(studios));}
function renderDevices(){ $('#equipment').innerHTML=devices.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join(''); $('#equipmentChecks').innerHTML=devices.map(d=>`<label class="check"><input type="checkbox" data-dev="${esc(d)}">${esc(d)}</label>`).join(''); $('#deviceList').innerHTML=devices.map((d,i)=>`<div class="card row"><b>${esc(d)}</b><button class="danger" onclick="removeDevice(${i})">Hapus</button></div>`).join(''); }
function renderStudios(){ $('#studioList').innerHTML=studios.map((s,si)=>`<div class="card"><div class="row"><h3>${esc(s)}</h3><button class="danger" onclick="removeStudio(${si})">Hapus</button></div>${devices.map((d,di)=>`<div class="card"><b>${esc(d)}</b><div class="status"><button class="okbtn" data-key="${si}-${di}" onclick="setStatus(this,'OK')">OK</button><button class="badbtn" data-key="${si}-${di}" onclick="setStatus(this,'TIDAK OK')">Tidak OK</button></div><label>Foto perangkat<input type="file" accept="image/*" capture="environment" onchange="uploadCheck(this,${si},${di})"></label><div id="photo-${si}-${di}"></div><label>Keterangan<textarea id="note-${si}-${di}" placeholder="Keterangan kondisi..."></textarea></label><button class="primary" onclick="saveCheck(${si},${di})">Simpan Pemeriksaan</button></div>`).join('')}</div>`).join(''); }
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
window.removeDevice=i=>{if(confirm('Hapus perangkat ini?')){devices.splice(i,1);save();renderDevices();renderStudios();}};
window.removeStudio=i=>{if(confirm('Hapus studio ini?')){studios.splice(i,1);save();renderStudios();}};
$('#addDevice').onclick=()=>{let n=prompt('Nama perangkat baru:');if(n&&n.trim()){devices.push(n.trim());save();renderDevices();renderStudios();}};
$('#addStudio').onclick=()=>{let n=prompt('Nama studio baru:');if(n&&n.trim()){studios.push(n.trim());save();renderStudios();}};
let statuses={};window.setStatus=(b,v)=>{statuses[b.dataset.key]=v; b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');};
async function post(data){let url=localStorage.getItem('wk_script_url');if(!url)throw Error('URL Apps Script belum diisi di Pengaturan.');let r=await fetch(url,{method:'POST',body:JSON.stringify(data)});return await r.json();}
$('#usageForm').onsubmit=async e=>{e.preventDefault();let selected=[...$('#equipment').selectedOptions].map(o=>o.value);let checks={};$$('#equipmentChecks input').forEach(x=>checks[x.dataset.dev]=x.checked);try{await post({action:'usage',date:$('#date').value,unit:$('#unit').value,duration:$('#duration').value,equipment:$('#equipmentName').value||selected.join(', '),checks,note:$('#usageNote').value});$('#msg').textContent='Tersimpan ke Google Spreadsheet.';e.target.reset();$('#date').value=new Date().toISOString().slice(0,10);}catch(err){$('#msg').textContent=err.message;}};
window.uploadCheck=async(input,si,di)=>{let f=input.files[0];if(!f)return;let reader=new FileReader();reader.onload=()=>{input.dataset.data=reader.result;$('#photo-'+si+'-'+di).innerHTML='<img class="photo" src="'+reader.result+'">';};reader.readAsDataURL(f);};
window.saveCheck=async(si,di)=>{let studio=studios[si],device=devices[di],key=si+'-'+di;let fileInput=$$('#studioList input[type=file]')[si*devices.length+di];let note=$('#note-'+key).value;let status=statuses[key]||'OK';let img=fileInput?.dataset.data||'';try{let r=await post({action:'inspection',studio,device,status,note,image:img,date:$('#date').value});alert(r.message||'Pemeriksaan tersimpan');}catch(e){alert(e.message)}};
$('#saveSettings').onclick=()=>{localStorage.setItem('wk_script_url',$('#scriptUrl').value.trim());alert('Pengaturan disimpan.');};
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');});
renderDevices();renderStudios();
