const SPREADSHEET_ID='1-Du8e4omNwqm-mCtP-n8dCw66mWgiCwlWMmdKSYja8M';
const USAGE_HEADERS=['No','DD/MM/YY','Unit Bisnis','Durasi Pemakaian','Nama Peralatan','Tripod','Kamera','Tv','Lampu 1','Lampu 2','Laptop','Kebersihan','Keterangan'];
const INSPECTION_HEADERS=['No','DD/MM/YY','Studio','Nama Perangkat','Foto','Status','Keterangan'];
function ss(){return SpreadsheetApp.openById(SPREADSHEET_ID)}
function setup(){let s=ss();let u=s.getSheetByName('Pemakaian')||s.insertSheet('Pemakaian');if(u.getLastRow()===0)u.appendRow(USAGE_HEADERS);let i=s.getSheetByName('Pemeriksaan Studio')||s.insertSheet('Pemeriksaan Studio');if(i.getLastRow()===0)i.appendRow(INSPECTION_HEADERS);let d=s.getSheetByName('Perangkat')||s.insertSheet('Perangkat');if(d.getLastRow()===0)d.appendRow(['Nama Perangkat','Aktif']);return ContentService.createTextOutput(JSON.stringify({ok:true,message:'Sheet siap'})).setMimeType(ContentService.MimeType.JSON)}
function doGet(){return setup()}
function doPost(e){try{let p=JSON.parse(e.postData.contents||'{}');let s=ss();if(p.action==='usage'){let sh=s.getSheetByName('Pemakaian')||s.insertSheet('Pemakaian');if(sh.getLastRow()===0)sh.appendRow(USAGE_HEADERS);let checks=p.checks||{};sh.appendRow([sh.getLastRow(),fmt(p.date),p.unit,p.duration,p.equipment,checks['Tripod']?'OK':'',checks['Kamera']?'OK':'',checks['TV']?'OK':'',checks['Lampu 1']?'OK':'',checks['Lampu 2']?'OK':'',checks['Laptop']?'OK':'',checks['Kebersihan']?'OK':'',p.note||'']);return out({ok:true,message:'Pemakaian tersimpan'})}if(p.action==='inspection'){let sh=s.getSheetByName('Pemeriksaan Studio')||s.insertSheet('Pemeriksaan Studio');if(sh.getLastRow()===0)sh.appendRow(INSPECTION_HEADERS);let photo='';if(p.image){let blob=Utilities.newBlob(Utilities.base64Decode(p.image.split(',').pop()),'image/jpeg',`${p.studio}-${p.device}-${Date.now()}.jpg`);let file=DriveApp.createFile(blob);photo=file.getUrl();}sh.appendRow([sh.getLastRow(),fmt(p.date),p.studio,p.device,photo,p.status,p.note||'']);return out({ok:true,message:'Pemeriksaan tersimpan',photo})}return out({ok:false,message:'Action tidak dikenal'})}catch(err){return out({ok:false,message:String(err)})}}
function fmt(d){if(!d)return Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'dd/MM/yy');let x=new Date(d+'T00:00:00');return Utilities.formatDate(x,Session.getScriptTimeZone(),'dd/MM/yy')}
function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
